repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint-cli2.yaml"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, yaml, json]
        args: ["--write"]

  - repo: local
    hooks:
      - id: ruff
        name: ruff lint
        entry: uvx ruff check --fix
        language: system
        types: [python]
        exclude: ^(\.venv/|_deprecated/)
      - id: ruff-format
        name: ruff format
        entry: uvx ruff format
        language: system
        types: [python]
        exclude: ^(\.venv/|_deprecated/)
      - id: check-upstream
        name: check for upstream changes
        entry: .githooks/check-upstream
        language: system
        pass_filenames: false
        always_run: true
