name: Quality Checks

on:
  push:
    branches: ["main"]
    paths-ignore:
      # Documentation and metadata
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - "**.md"
      # Version and config
      - "**/__version__.py"
      - ".gitignore"
      - ".editorconfig"
      - ".prettierrc"
      - "Makefile"
      # Images and diagrams
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.svg"
      - "**/*.gif"
      # Directories
      - ".vscode/**"
      - "docs/**"
      - "examples/**"
      - "scripts/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      # Documentation and metadata
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - "**.md"
      # Version and config
      - "**/__version__.py"
      - ".gitignore"
      - ".editorconfig"
      - ".prettierrc"
      - "Makefile"
      # Images and diagrams
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.svg"
      - "**/*.gif"
      # Directories
      - ".vscode/**"
      - "docs/**"
      - "examples/**"
      - "scripts/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install ruff pytest pytest-cov pytest-asyncio
          pip install .

      - name: Lint with ruff
        run: ruff check .

      - name: Check formatting with ruff
        run: ruff format --check .

      - name: Run pytest with coverage
        run: pytest --cov=gac --cov-report=xml -s

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cellwebb/gac

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
