name: Nightly Release

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: "0 */2 * * *" # Run every two hours to check for idle time

# Add permissions at workflow level
permissions:
  contents: write # Required for creating GitHub releases
  packages: write # Required for publishing packages

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check_idle.outputs.should_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for checking commits

      - name: Check if repo has been idle for at least 1 hour
        id: check_idle
        run: |
          # Get the timestamp of the most recent commit
          LATEST_COMMIT_TIMESTAMP=$(git log -1 --format=%ct)
          CURRENT_TIMESTAMP=$(date +%s)

          # Calculate time difference in seconds
          TIME_DIFF=$((CURRENT_TIMESTAMP - LATEST_COMMIT_TIMESTAMP))

          # Check if it's been at least 1 hour (3600 seconds) since the last commit
          if [ $TIME_DIFF -ge 3600 ]; then
            echo "Last commit was $TIME_DIFF seconds ago (more than 1 hour)"
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "Last commit was $TIME_DIFF seconds ago (less than 1 hour)"
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if nightly has already been released today
        if: steps.check_idle.outputs.should_release == 'true'
        id: check_existing
        run: |
          TODAY=$(date +"%Y%m%d")
          # Check if a nightly tag exists for today
          if git tag -l | grep -q "nightly-$TODAY"; then
            echo "A nightly release for today already exists"
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "No nightly release for today exists yet"
          fi
